doc(cert_info): Extend documentation

diff --git a/extend/cert_info b/extend/cert_info
--- a/extend/cert_info
+++ b/extend/cert_info
@@ -1,6 +1,7 @@
 #!/bin/sh
 
 # cert_info
+# author: Václav Brožík
 #
 # Get information about a certificate stored in a file.
 # Currently supports only PKCS#12 certificate files.
@@ -8,21 +9,36 @@
 # Designed to be used on Check Point Gaia R80.40+ to check
 # ICA and SIC certificates.
 
-# TODO
-# * openssl x509 -enddate -noout -in my.pem -checkend 604800
+# Installation on Gaia
+# --------------------
+# 1. Copy the script to /usr/local/bin
+# 2. Add settings into /etc/snmp/userDefinedSettings.conf
+#    extend cert_ica_expu /usr/local/bin/cert_info ica expiration unix
+#    See other examples in userDefinedSettings_examples.conf.
+# 3. Restart snmp agent:
+#    clish -c 'set snmp agent off' && clish -c 'set snmp agent on'
+# 4. Test:
+#    snmptable localhost NET-SNMP-EXTEND-MIB::nsExtendOutput1Table
+#    snmpget localhost 'NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."cert_ica_expi"'
 
-# installation on Gaia:
-# /etc/snmp/userDefinedSettings.conf
-# extend cert_ica_exp /usr/local/bin/cert_info ica expiration
-# extend cert_sic_exp /usr/local/bin/cert_info sic expiration
-
-# clish -c 'set snmp agent off' && clish -c 'set snmp agent on'
-
-# test
-# snmptable localhost NET-SNMP-EXTEND-MIB::nsExtendOutput1Table
-# snmptable localhost NET-SNMP-EXTEND-MIB::nsExtendOutput2Table
-# snmpwalk localhost NET-SNMP-EXTEND-MIB::nsExtendOutput1Line
-# snmpget localhost 'NET-SNMP-EXTEND-MIB::nsExtendOutput1Line."cert_ica_expi"'
+# Usage
+# -----
+# The program has 3 mandatory arguments:
+# cert_info <cert_type> <information> <conversion>
+# <cert_type>   - type of certificate to get information about
+#               - ica - ICA root certificate (on management servers only)
+#               - sic - machine's SIC certificate - on any managed machine
+#                   TODO: support for VS SIC certificates
+# <information> - information to retrieve
+#               - expiration - expiration date-time
+#               - exp2months, exp3months - whether certificate expires
+# <conversion>  - conversion of the information (output format)
+#               - unix - Unix epoch time (number of seconds since 1970-01-01)
+#               - iso-8601-compact-date - date in format: YYYYMMDD
+#               - identity - pass the information unmodified
+#                   for expN* it passes OK or Expires
+# When the program fails, it returns, status 1, text 'Failed' in the first line
+# and details in the second line.
 
 # openssl on Check Point Gaia:
 openssl=cpopenssl
@@ -39,7 +55,7 @@ if test $# != 3 ; then
     errexit 'Tool cert_info requires three arguments.'
 fi
 
-# certificate file locations:
+# --- certificate file locations:
 case "$1" in
     ica)
         cert_file="$FWDIR/conf/InternalCA.p12"
@@ -51,6 +67,7 @@ case "$1" in
         errexit "Unknown certificate type, got: '$1'"
 esac
 
+# --- information extraction
 sed_filter_checkend='s/^Certificate will expire/Expires/p;s/^Certificate will not expire/OK/p'
 case "$2" in
     expiration)
@@ -69,7 +86,7 @@ case "$2" in
         errexit "Unknown query type, got: '$2'"
 esac
 
-# information conversion
+# --- output conversion
 case "$3" in
     unix)
         convert () {
@@ -90,13 +107,20 @@ case "$3" in
         errexit "Unknown conversion, got: '$3'"
 esac
 
+# Option for extended error checking. Not in current POSIX1.2017.
+# Not in dash which is /bin/sh in Debian and derivatives (Ubuntu)!
+# shellcheck disable=SC3040
+# set -o pipefail 2>/dev/null
+# Non-zero exit status of the pipe not tested because -checkend returns nonzero
+# when certificate will fail.
+
 # shellcheck disable=SC2086
 output=$(
     "$openssl" pkcs12 -in "$cert_file" -nokeys -nomacver -passin pass: 2>/dev/null |
     "$openssl" x509 $x509_opt 2>/dev/null |
     sed -n "$sed_filter")
 
-# check and write the result
+# --- check and write the result
 test -z "$output" && errexit 'Query failed - empty output.'
 
 output=$(convert "$output" 2>/dev/null) || errexit 'Conversion failed.'
